CuaHangMyPham/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns= [

#---------------------------------------------------------------------------------------------------------------------#
#--------------------------------------------------------TRANG CỬA HÀNG-----------------------------------------------#
#---------------------------------------------------------------------------------------------------------------------# 
    path('', views.index, name='index'),
    path('news/', views.news, name='news'),
    path('shop/', views.shop, name='shop'),
    path('shop_detail/<int:sp_id>/', views.shop_detail, name='shop_detail'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('session_info/', views.session_info, name='session_info'),
    path('logout/', views.auth_logout, name='auth_logout'),
    path('cart/', views.cart, name='cart'),
    path('shop_theoloai/<int:ml>/', views.DSSPTheoLoai, name='DSSPTheoLoai'),
    path('shop_ThuongHieu/<int:ml>/', views.DSSPTheoTH, name='DSSPTheoTH'),
    path('checkout/', views.checkout, name='checkout'),
    path('order_details/', views.order_user, name='order_details'),



#----------------------------------------------------------GIỎ HÀNG---------------------------------------------------#   
    path('cart/', views.cart, name='cart'),
    path('addCart/', views.addProToCart, name='addCart'),
    path('clearCart/', views.clearCart, name='clearCart'),
    path('deleteOnePro/<int:product_id>/', views.deleteProFromCart, name='deleteOnePro'),
    path('increase_quantity/<int:product_id>/', views.increase_quantity, name='increase_quantity'),
    path('decrease_quantity/<int:product_id>/', views.decrease_quantity, name='decrease_quantity'),



#---------------------------------------------------------------------------------------------------------------------#
#--------------------------------------------------------TRANG ADMIN--------------------------------------------------#
#---------------------------------------------------------------------------------------------------------------------# 



#--------------------------------------TRANG CHỦ ADMIN--------------------------------------------#
    path('admin/', views.indexAdmin, name='index'),

#--------------------------------------QUẢN LÝ SẢN PHẨM--------------------------------------------#
    path('admin/products/', views.products, name='products'),
    path('admin/detail_product/<int:product_id>/', views.detail_product, name='detail_product'),
    path('admin/add_product/', views.add_product, name='add_product'),#thêm sản phẩm
    path('admin/edit_product/<int:id_product>/', views.edit_product, name='edit_product'),
    path('admin/products/<int:id>/delete', views.delete_product, name='delete_product'),#xóa sản phẩm


#--------------------------------------QUẢN LÝ THƯƠNG HIỆU--------------------------------------------#
    path('admin/brands/', views.brands, name='brands'),#danh sách thương hiệu
    path('admin/add_brand/', views.add_brand, name='add_brand'),#thêm thương hiệu
    path('admin/edit_brand/<int:id_brand>/', views.edit_brand, name='edit_brand'),#sửa thương hiệu
    path('delete_brand/<int:id_brand>/', views.delete_brand, name='delete_brand'),#xóa thương hiệu

#--------------------------------------QUẢN LÝ LOẠI HÀNG--------------------------------------------#
    path('admin/categorys/', views.categorys, name='categorys'),#danh sách loại hàng
    path('admin/detail_category/<int:id_category>/', views.detail_category, name='detail_category'),#xem chi tiết loại hàng
    path('admin/add_category/', views.add_category, name='add_category'),#thêm loại hàng
    path('admin/edit_category/<int:id_category>/', views.edit_category, name='edit_category'),#sửa loại hàng
    path('admin/categorys/<int:id_category>/delete', views.delete_category, name='delete_category'),#xóa loại hàng

#--------------------------------------QUẢN LÝ ĐƠN HÀNG--------------------------------------------#
    path('admin/orders/', views.orders, name='orders'), #danh sách đơn hàng
    path('admin/detail_order/<int:id_order>/', views.detail_order, name='detail_order'), #chi tiết đơn hàng
    
#--------------------------------------QUẢN LÝ NGƯỜI DÙNG--------------------------------------------#
    path('admin/users/', views.users, name='users'), #danh sách người dùng
    path('admin/add_user/', views.add_user, name='add_user'), #thêm người dùng
    path('admin/users/<int:user_id>/delete', views.delete_user, name='delete_user'),
    path('admin/edit_user/<int:user_id>/', views.edit_user, name='edit_user'), #sửa người dùng


]

QL_CHMYPHAM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path("admin/", admin.site.urls),
    path('', include('CuaHangMyPham.urls')),
    #path('admin/', include('Admin.urls'))
]

CuaHangMyPham/models.py
from django.db import models

# Create your models here.

# class Category_Group(models.Model):
#     id = models.AutoField(primary_key=True)
#     name = models.CharField(max_length=100)

class Category(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    #categroup = models.ForeignKey(Category_Group, on_delete=models.SET_NULL, null=True)

class Brand(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    # description = models.TextField()
    # image = models.TextField()

class Product(models.Model):
    id = models.AutoField(primary_key=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2) #decimal_places xác định số chữ số thập phân sau dấu chấm thập phân.
    description = models.TextField()
    image = models.TextField()
    # SoLuongTon = models.IntegerField(default=0)
    # HinhAnh = models.ImageField(upload_to='images/')

class User(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=255)
    role = models.CharField(max_length=20, default='user')

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    
    class Meta:
        unique_together = ('user', 'product')

class Order(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_date = models.DateTimeField(auto_now_add=True)
    recipient_name = models.CharField(max_length=100)
    recipient_phone = models.CharField(max_length=20)
    recipient_address = models.CharField(max_length=255)
    method_payment = models.CharField(max_length=100, blank=True, null=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=100, default="Chưa xác nhận")

class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    class Meta:
        # Định nghĩa hai trường foreign key làm khóa chính
        unique_together = ('order', 'product')

CuaHangMyPham/forms.py
import re
from django import forms
from .models import Category, Brand, User,Product, Order, OrderDetail
#import re 
# from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        self.fields['name'].error_messages = {'required': 'Tên không được để trống'}

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if Category.objects.filter(name=name).exists():
            raise forms.ValidationError("Loại đã tồn tại")
        return name
    

class BrandForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = ['name']
        error_messages = {
            'name': {
                'required': "Tên thương hiệu không được để trống",
            },
        }

    # *args là một tuple chứa các đối số không đặt tên.
    # **kwargs là một từ điển chứa các đối số từ khóa.
    def __init__(self, *args, **kwargs):
        # lấy giá trị của khóa 'instance' từ kwargs nếu có, nếu không thì trả về None.
        self.instance = kwargs.get('instance', None)
        super(BrandForm, self).__init__(*args, **kwargs)

# Phương thức này sẽ tự động được gọi khi gọi is_valid() trên form
    def clean_name(self):
        name = self.cleaned_data.get('name')
        
        if not name:
            raise forms.ValidationError("Tên thương hiệu không được để trống")
        # exclude(pk=self.instance.pk): Loại trừ đối tượng hiện tại (nếu đang chỉnh sửa) ra khỏi danh sách kiểm tra. tức là loại bỏ các đối tượng có pk = pk trong csdl
        if Brand.objects.filter(name=name).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError("Thương hiệu đã tồn tại")
        return name

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['recipient_name', 'recipient_address', 'recipient_phone', 'method_payment']
        
    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['recipient_name'].error_messages = {'required': 'Tên không được để trống'}
        self.fields['recipient_address'].error_messages = {'required': 'Địa chỉ không được để trống'}
        self.fields['recipient_phone'].error_messages = {'required': 'Số điện thoại không được để trống'}
        self.fields['method_payment'].error_messages = {'required': 'Phương thức thanh toán không được để trống'}

    def clean_recipient_phone(self):
        recipient_phone = self.cleaned_data.get('recipient_phone')
        if not recipient_phone:
            raise forms.ValidationError("Số điện thoại không được để trống")
        if not recipient_phone.isdigit() or not re.match(r"^0\d{9}$", recipient_phone) or len(recipient_phone) > 10:
            raise forms.ValidationError("Số điện thoại không hợp lệ!")
        return recipient_phone

class OrderDetailForm(forms.ModelForm):
    class Meta:
        model = OrderDetail
        fields = ['product', 'quantity']

class UpdateOrderStatusForm(forms.Form):
    status = forms.CharField(max_length=100)
    
    
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name', 'email', 'phone', 'password', 'role']

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['name'].error_messages = {'required': 'Tên không được để trống'}
        self.fields['email'].error_messages = {'required': 'Email không được để trống'}
        self.fields['phone'].error_messages = {'required': 'Số điện thoại không được để trống'}
        self.fields['password'].error_messages = {'required': 'Mật khẩu không được để trống'}
        self.fields['role'].error_messages = {'required': 'Vai trò không được để trống'}

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if not name:
            raise forms.ValidationError("Tên không được để trống")
        return name

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email:
            raise forms.ValidationError("Email không được để trống")
        if not re.match(r"[^@]+@[^@]+\.[^@]+", email):
            raise forms.ValidationError("Email không hợp lệ")
        return email

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if not phone:
            raise forms.ValidationError("Số điện thoại không được để trống")
        if not re.match(r"0[0-9]{9}", phone):
            raise forms.ValidationError("Số điện thoại không hợp lệ")
        return phone

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if not password:
            raise forms.ValidationError("Mật khẩu không được để trống")
        if len(password) < 8:
            raise forms.ValidationError("Mật khẩu phải có ít nhất 8 ký tự")
        if not re.match(r"[A-Za-z0-9@#$%^&+=]{8,}", password):
            raise forms.ValidationError('Mật khẩu phải chứa ít nhất một chữ cái và một số')
        return password

    def clean_role(self):
        role = self.cleaned_data.get('role')
        if not role:
            raise forms.ValidationError("Vai trò không được để trống")
        return role
    

class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['email'].error_messages = {'required': 'Email không được để trống'}
        self.fields['password'].error_messages = {'required': 'Mật khẩu không được để trống'}

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email:
            raise forms.ValidationError("Email không được để trống")
        if not re.match(r"[^@]+@[^@]+\.[^@]+", email):
            raise forms.ValidationError("Email không hợp lệ")
        return email
    
    def clean_password(self):
        password = self.cleaned_data.get('password')
        if not password:
            raise forms.ValidationError("Mật khẩu không được để trống")
        if len(password) < 8:
            raise forms.ValidationError("Mật khẩu phải có ít nhất 8 ký tự")
        if not re.match(r"[A-Za-z0-9@#$%^&+=]{8,}", password):
            raise forms.ValidationError('Mật khẩu phải chứa ít nhất một chữ cái và một số')
        return password
    
    
class SignUpForm(forms.ModelForm):
    confirm_password = forms.CharField(widget=forms.PasswordInput, error_messages={'required': 'Nhập lại mật khẩu không được để trống'})

    class Meta:
        model = User
        fields = ['name', 'email', 'phone', 'password']

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['name'].error_messages = {'required': 'Tên không được để trống'}
        self.fields['email'].error_messages = {'required': 'Email không được để trống'}
        self.fields['phone'].error_messages = {'required': 'Số điện thoại không được để trống'}
        self.fields['password'].error_messages = {'required': 'Mật khẩu không được để trống'}

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email:
            raise forms.ValidationError("Email không được để trống")
        if not re.match(r"[^@]+@[^@]+\.[^@]+", email):
            raise forms.ValidationError("Email không hợp lệ")
        return email

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if not phone:
            raise forms.ValidationError("Số điện thoại không được để trống")
        if not re.match(r"0[0-9]{9}", phone):
            raise forms.ValidationError("Số điện thoại không hợp lệ")
        return phone

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if not password:
            raise forms.ValidationError("Mật khẩu không được để trống")
        if len(password) < 8:
            raise forms.ValidationError("Mật khẩu phải có ít nhất 8 ký tự")
        if not re.match(r"[A-Za-z0-9@#$%^&+=]{8,}", password):
            raise forms.ValidationError('Mật khẩu phải chứa ít nhất một chữ cái và một số')
        return password

    def clean_confirm_password(self):
        confirm_password = self.cleaned_data.get('confirm_password')
        password = self.cleaned_data.get('password')
        if confirm_password != password:
            raise forms.ValidationError("Mật khẩu không khớp")
        return confirm_password
        
    
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['category', 'brand', 'name', 'price', 'description', 'image']


    
    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['category'].error_messages = {'required': 'Loại không được để trống'}
        self.fields['brand'].error_messages = {'required': 'Thương hiệu không được để trống'}
        self.fields['name'].error_messages = {'required': 'Tên sản phẩm không được để trống'}
        self.fields['price'].error_messages = {'required': 'Giá không được để trống'}
        self.fields['description'].error_messages = {'required': 'Mô tả khẩu không được để trống'}
        self.fields['image'].error_messages = {'required': 'Hình không được để trống'}

    def clean_name(self):
        name = self.cleaned_data['name']
        return name

CuaHangMyPham/templates/page/about.html
{% extends "pages/layout.html" %}
{% block title %}
    Giới thiệu
{% endblock %}

{% block content %}
{% load static %}
<div id="content">
    <div class="container d-flex justify-content-around">
        <div class="sub">
            <h2>Giới thiệu</h2>
            <p class="fw-bold">Về The Face Shop</p>
            <p>Slogan: Vẻ đẹp của bạn, niềm tự hào của chúng tôi</p>
            <ul>
                <li>Sứ mệnh: Luôn mang đến những sẳn phẩm chính hãng, chất lượng, tiết kiệm thời gian và tiền bạc cho khách hàng.</li>
                <li>Giá trị cốt lõi: "Chữ tín - Trách nhiệm - Tin cậy"</li>
                <li>Chữ tín: Lấy chữ Tín làm vũ khí cạnh tranh và bảo vệ chữ Tín là bảo vệ danh dự của chính mình.</li>
                <li>Trách nhiệm: Luôn nhận lỗi sai khi có sai sót của công ty.</li>
                <li>
                    Tin cậy: sự tin cậy của khách hàng là tiêu chuẩn cần thiết đầu tiên mà chúng tôi coi trọng nhất, thậm chí cao hơn các giá trị tài chính.sự tin cậy của khách hàng là tiêu chuẩn cần thiết đầu tiên mà chúng tôi coi trọng nhất, thậm
                    chí cao hơn các giá trị tài chính.
                </li>
                <li>
                    Thông tin liên hệ:
                    <ul>
                        <li>Hotline: 1900 8198</li>
                        <li>Email: contact@thefaceshop.com.vn</li>
                    </ul>
                </li>
                <li>Địa chỉ: THE FACE SHOP, 167 Nam Kỳ Khởi Nghĩa, Quận 1, Thành phố Hồ Chí Minh.</li>
            </ul>
        </div>
        <div>
            <img class="img-fluid" src="{% static 'img/gioithieu.jpg' %}" />
        </div>
    </div>
</div>



{% endblock %}

CuaHangMyPham/templates/page/cart.html
{% extends "pages/layout.html" %} {% block title %} Giỏ hàng {% endblock %} {% block content %} {% load static %}
<!--Body Content-->
<br>
<form action="#" method="post" style="width: auto;">
    <section class="h-100" style="background-color: white">
        <div class="container h-100 py-3">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-10">

                    <div class="d-flex justify-content-between align-items-center mb-4">
                        <h3 class="fw-normal mb-0 text-black">Shopping Cart</h3>
                        <div>
                            {% if cart_items %}

                            <div class="row d-flex align-items-center">

                                <div class="col-auto">Tổng tiền: {{ total_price|floatformat:0 }} VNĐ</div>

                                <div class="col-auto"><a href="/clearCart" class="btn--link cart-continue"><i class="fa-solid fa-xmark"></i> Xóa tất cả</a></div>
                            </div>
                            <!-- <p class="mb-0"><span class="text-muted"></span> </p> -->
                            {% else %}
                            <div></div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="card rounded-3 mb-4">
                        <div class="card-body p-2" style="background-color: lightpink;">
                            <div class="row d-flex justify-content-between align-items-center">
                                <div class="col-md-2 col-lg-2 col-xl-2">

                                </div>
                                <div class="col-md-4 col-lg-4 col-xl-4">
                                    <b>Sản phẩm</b>
                                </div>

                                <div class="col-md-2 col-lg-2 col-xl-1 d-flex">
                                    <b>Số lượng</b>

                                </div>


                                <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                    <b>Giá</b>
                                </div>
                                <div class="col-md-1 col-lg-1 col-xl-1 text-end">

                                </div>
                            </div>
                        </div>
                    </div>
                    {% if cart_items %} {% for item in cart_items %}
                    <div class="card rounded-3 mb-4">
                        <div class="card-body p-4">
                            <div class="row d-flex justify-content-between align-items-center">
                                <div class="col-md-2 col-lg-2 col-xl-2">
                                    <img src="{% static 'img/'%}{{item.product.image}}" class="img-fluid rounded-3" alt="Cotton T-shirt">
                                </div>
                                <div class="col-md-4 col-lg-4 col-xl-4">
                                    <p style="font-size: 18px;" class="lead fw-normal mb-2">{{ item.product.name }}</p>
                                    <p><span class="text-muted"> Loại:  </span>{{ item.product.category.name }}</p>
                                </div>

                                <div class="col-md-2 col-lg-2 col-xl-1 d-flex">
                                    <a href="/decrease_quantity/{{item.product.id}}" class="btn btn-link px-2">
                                        <i class="fas fa-minus"></i>
                                    </a>
                                    <div style="border: 1px solid #ccc; border-radius: 5px; padding: 5px 10px;   ">{{ item.quantity }}</div>
                                    <!-- <input id="form1" min="0" name="quantity" value="" type="number" class="form-control form-control-sm" /> -->
                                    <a href="/increase_quantity/{{item.product.id}}" class="btn btn-link px-2">
                                        <i class="fas fa-plus"></i>
                                    </a>
                                </div>


                                <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                    <h6 class="mb-0">{{ item.item_total|floatformat:0}} VNĐ</h6>
                                </div>
                                <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                                    <a href="/deleteOnePro/{{item.product.id}}" class="text-danger"><i class="fas fa-trash fa-lg"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="card">
                        <div class="card-body">
                            <a href="{% url 'checkout' %}" data-mdb-button-init data-mdb-ripple-init class="btn btn-warning btn-block btn-lg">Đặt Hàng</a>
                        </div>
                    </div>
                    {% else %}
                    <div>Chưa có sản phẩm nào trong giỏ hàng</div>
                    {% endif %}



                </div>
            </div>
        </div>
    </section>

</form>



{% endblock %}

CuaHangMyPham/templates/page/login.html
{% extends "pages/layout.html" %}
{% block title %}
    Đăng nhập
{% endblock %}

{% block content %}
{% load static %}

<div id="main">
    <div id="content">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6" style="background-color: lightblue; border-radius: 30px; padding: 30px">
                    <h2 class="w-100 text-center p-3 text-danger"> Đăng nhập</h2>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="form-group">
                            <label for="id_email">Email</label>
                            <input name="email" type="text" class="form-control" id="id_email" value="{{ form.email.value|default_if_none:'' }}">
                            {% if form.email.errors %}
                            <span class="text-danger">{{ form.email.errors }}</span>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="id_password">Mật khẩu</label>
                            <input name="password" type="password" class="form-control" id="id_password" value="{{ form.password.value|default_if_none:'' }}">
                            {% if form.password.errors %}
                            <span class="text-danger">{{ form.password.errors }}</span>
                            {% endif %}
                        </div>
                        <div class="text-center mt-2" style=" display: flex; justify-content: center;">
                            <button type="submit" class="btn btn-primary">Đăng nhập</button>
                        </div>
                    </form>              
                </div>
            </div>
        </div>
        
    </div>
</div>


{% endblock %}

CuaHangMyPham/templates/page/signup.html
{% extends "pages/layout.html" %}
{% block title %}
    Đăng ký
{% endblock %}

{% block content %}
{% load static %}
<div id="main">
    <div id="content">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6" style="background-color: lightblue; border-radius: 30px; padding: 30px">
                    <h2 class="w-100 text-center p-3 text-danger"> Đăng ký</h2>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="form-group">
                            <label for="id_name">Tên</label>
                            <input name="name" type="text" class="form-control" id="id_name" value="{{ form.name.value|default_if_none:'' }}">
                            {% if form.name.errors %}
                            <span class="text-danger">{{ form.name.errors }}</span>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="id_email">Email</label>
                            <input name="email" type="text" class="form-control" id="id_email" value="{{ form.email.value|default_if_none:'' }}">
                            <span class="text-danger">{{ form.email.errors }}</span>
                        </div>
                        <div class="form-group">
                            <label for="id_phone">Số điện thoại</label>
                            <input name="phone" type="text" class="form-control" id="id_phone" value="{{ form.phone.value|default_if_none:'' }}">
                            <span class="text-danger">{{ form.phone.errors }}</span>
                        </div>
                        <div class="form-group">
                            <label for="id_password">Mật khẩu</label>
                            <input name="password" type="password" class="form-control" id="id_password" value="{{ form.password.value|default_if_none:'' }}">
                            <span class="text-danger">{{ form.password.errors }}</span>
                        </div>
                        <div class="form-group">
                            <label for="id_confirm_password">Nhập lại mật khẩu</label>
                            <input name="confirm_password" type="password" class="form-control" id="id_confirm_password" value="{{ form.confirm_password.value|default_if_none:'' }}">
                            <span class="text-danger">{{ form.confirm_password.errors }}</span>
                        </div>
                        <div class="text-center mt-2" style=" display: flex; justify-content: center;">
                            <button type="submit" class="btn btn-primary">Đăng ký</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}